"""Add common market data tables: Instrument, TradingCalendar, EodBar

Revision ID: f7b0766c55ad
Revises: 0005
Create Date: 2026-08-19 15:25:00.491291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f7b0766c55ad'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Instrument',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('underlying_symbol', sa.String(length=50), nullable=True),
    sa.Column('instrument_type', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('first_traded_date', sa.Date(), nullable=True),
    sa.Column('last_traded_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index('ix_instrument_underlying', 'Instrument', ['underlying_symbol'], unique=False)
    op.create_table('TradingCalendar',
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('is_trading_day', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('calendar_date')
    )
    op.create_table('EodBar',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=14, scale=4), nullable=False),
    sa.Column('high', sa.DECIMAL(precision=14, scale=4), nullable=False),
    sa.Column('low', sa.DECIMAL(precision=14, scale=4), nullable=False),
    sa.Column('close', sa.DECIMAL(precision=14, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('open_interest', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['Instrument.id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'trade_date')
    )
    op.create_index('ix_eod_bar_date', 'EodBar', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_eod_bar_date', table_name='EodBar')
    op.drop_table('EodBar')
    op.drop_table('TradingCalendar')
    op.drop_index('ix_instrument_underlying', table_name='Instrument')
    op.drop_table('Instrument')
    # ### end Alembic commands ###
